Updated test to validate energy values
dwave-examples/knapsack pull request #15
Opened 2020-09-18 23:14 UTC by hemantdwave

Please review updated energy values in test , which fails on hybrid_v2 solver.

2020-09-20 17:10 UTC, randomir approved these changes

2020-09-20 17:15 UTC, randomir requested changes
Energy upper bound was not updated in the `while` loop.

Suggestion: define valid energy bounds in variables at the top, and use them through the test case.

Unrelated, `import re` can be moved to file beginning. Also, since you capitalized the string, `re.I` is not needed.

2020-10-16 20:12 UTC, randomir commented
@hemantdwave, would you prefer I make those changes requested, so we can merge this PR?

2020-10-16 21:19 UTC, hemantdwave commented
Updated as per review comments please check,thanks

2020-10-19 12:14 UTC, merged